version: '3.7'

services:
    backend:
        tty: true
        #uvicorn wsgi:app --reload --host 0.0.0.0
        #command: python manage.py runserver --settings=config.settings_dev 0.0.0.0:9000
        command: dev
        build:
            dockerfile: Dockerfile
            context: ./backend/
        volumes:
            - ./backend:/app/
        ports:
            - 8000:8000
        env_file:
            - env.dev
