# Generated by Django 4.2.4 on 2023-08-23 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_conversations', '0004_alter_message_extra_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='message_id',
            field=models.CharField(default='123', max_length=255, unique=True),
            preserve_default=False,
        ),
    ]
