# Generated by Django 4.2.4 on 2023-08-23 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_conversations', '0005_message_message_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='direction',
            field=models.CharField(choices=[('inbound', 'inbound'), ('outbound', 'outbound')], default=1, max_length=10),
            preserve_default=False,
        ),
    ]
