# Generated by Django 4.2.4 on 2023-08-23 02:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_conversations', '0006_message_direction'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='source',
            new_name='target',
        ),
    ]
