# Generated by Django 4.2.4 on 2023-08-30 00:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_conversations', '0008_alter_message_extra_details_alter_message_target_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversation',
            name='target',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversations', to='user_conversations.usernumber'),
        ),
        migrations.AlterField(
            model_name='message',
            name='conversation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='conversation', to='user_conversations.conversation'),
        ),
    ]
