# Generated by Django 4.2.4 on 2023-08-31 21:08

from django.db import migrations, models
import user_conversations.models


class Migration(migrations.Migration):

    dependencies = [
        ('user_conversations', '0010_alter_message_conversation_messagemedia'),
    ]

    operations = [
        migrations.AddField(
            model_name='messagemedia',
            name='media_message_id',
            field=models.CharField(default='123', max_length=255, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='message',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='messagemedia',
            name='file',
            field=models.FileField(upload_to=user_conversations.models.message_media_path),
        ),
    ]
