# Generated by Django 4.2.4 on 2023-08-31 22:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_conversations', '0011_messagemedia_media_message_id_alter_message_content_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='conversation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='user_conversations.conversation'),
        ),
    ]
